//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificate
    {
        public Certificate()
        {
            this.Questions = new HashSet<Question>();
            this.QuestionComments = new HashSet<QuestionComment>();
            this.Skills = new HashSet<Skill>();
        }
    
        public int CertificateId { get; set; }
        public string CompanyName { get; set; }
        public string CertificateCode { get; set; }
        public string CertificateName { get; set; }
        public string Technology { get; set; }
        public System.DateTime PublishDate { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<QuestionComment> QuestionComments { get; set; }
        public virtual ICollection<Skill> Skills { get; set; }
    }
}
