//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionLevel
    {
        public QuestionLevel()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int QuestionLevelId { get; set; }
        public string QuestionLevelName { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
    }
}
