//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionComment
    {
        public long QuestionCommentId { get; set; }
        public int QuestionId { get; set; }
        public string UserId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CommentDate { get; set; }
        public string Email { get; set; }
        public string FullName { get; set; }
        public Nullable<long> ParrentCommentId { get; set; }
        public Nullable<bool> Confirmed { get; set; }
        public string ConfirmedBy { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
