//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionVote
    {
        public long QuestionVoteId { get; set; }
        public long QuestionId { get; set; }
        public string UserId { get; set; }
        public int Vote { get; set; }
        public System.DateTime VoteDate { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual UserProfile UserProfile { get; set; }
    }
}
