//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.Questions = new HashSet<Question>();
            this.SkillDetails = new HashSet<SkillDetail>();
        }
    
        public int SkillId { get; set; }
        public string SkillName { get; set; }
        public int CertificateId { get; set; }
        public int SkillOrder { get; set; }
    
        public virtual Certificate Certificate { get; set; }
        public virtual ICollection<Question> Questions { get; set; }
        public virtual ICollection<SkillDetail> SkillDetails { get; set; }
    }
}
