//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillDetail
    {
        public SkillDetail()
        {
            this.Questions = new HashSet<Question>();
        }
    
        public int SkillDetailId { get; set; }
        public int SkillId { get; set; }
        public string SkillDetailDescription { get; set; }
        public Nullable<int> SkillDetailOrder { get; set; }
    
        public virtual ICollection<Question> Questions { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
